<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Signup\Module'                        => __DIR__ . '/Module.php',
    'Signup\Controller\IndexController' => __DIR__ . '/src/Signup/Controller/IndexController.php',
    'SignupTest\Framework\TestCase'        => __DIR__ . '/tests/Signup/Framework/TestCase.php',
    'SignupTest\SampleTest'                => __DIR__ . '/tests/Signup/SampleTest.php',
);
